@echo off
:loop
echo Запускаем программу...
python "D:\code\Python\Python\speedrun\27_fragment_check\main.py"
echo Ожидание 1 час...
timeout /t 3600 /nobreak >nul
echo Перезапускаем программу...
goto loop
